# Generated by Django 4.2 on 2024-09-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='profile_img',
        ),
    ]
